name: pikkup
description: A delivery app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  introduction_screen: ^3.0.1
  flutter_staggered_grid_view: ^0.6.1
  dots_indicator: ^2.1.0
  image_picker: ^0.8.5
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  flutter_multi_formatter: ^2.5.7
  credit_card_validator: ^2.0.1
  intl: ^0.17.0
  currency_text_input_formatter: ^2.1.7
  #font_awesome_flutter: ^10.1.0
  #mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

    - family: Sora
      fonts:
        - asset: fonts/Sora.ttf